### ISSUE TITLE
ibc-derive doesn’t work if Context type requires bounds

### ISSUE THREAD

**Issue by mina86** [cosmos/ibc-rs#1016]
## Feature Summary

ClientState derive requires context type to be specified through a `#[generics(...)]` annotation.  However, this doesn’t work if the context type is generic.  For example, consider the following:

```rust
use ibc::core::client::context::client_state::ClientState;

#[derive(ClientState)]
#[generics(/* ... */)]
enum AnyClientState {}

struct Context<'a>(&'a ());
```

What should be put inside of the generics annotation to make the code work? Using:

```rust
#[generics(
    ClientValidationContext = Context<'_>,
    ClientExecutionContext = Context<'_>,
)]
```

results in the proc macro failing to recognise the annotation and output the following message: AnyClientState must be annotated with `#[generics(ClientValidationContext = <your ClientValidationContext>, ClientExecutionContext: <your ClientExecutionContext>)]: Multiple errors: (expected `:``.  Removing the generic argument as in:

```rust
#[generics(
    ClientValidationContext = Context,
    ClientExecutionContext = Context,
)]
```

results in compilation failure:

```
error[E0726]: implicit elided lifetime not allowed here
 --> src/main.rs:5:31
  |
5 |     ClientValidationContext = Context,
  |                               ^^^^^^^ expected lifetime parameter
  |
help: indicate the anonymous lifetime
  |
5 |     ClientValidationContext = Context<'_>,
  |                                      ++++

```

## Proposal

For my use case it would be enough if generic attributes were recognised after the type.

**Comment by Farhad-Shabani** [comment]
Correct, the issue arises when dealing with contexts that involve generic types or lifetimes. We've got the same issue as reported in #910.

**Comment by mina86** [comment]
Ah, I see, sorry for the duplicate. #910 indeed covers this case.
