### ISSUE TITLE
Remove `trace_prefix` from the `denom` in `send_transfer`

### ISSUE THREAD

**Issue by dhruvja** [cosmos/ibc-rs#1022]
## Bug Summary

The `trace_prefix` is stripped from the coin denom in `on_recv_packet` shown below. https://github.com/cosmos/ibc-rs/blob/d96cc6632e53cbab1a4bb6f636a86427772806d8/ibc-apps/ics20-transfer/src/handler/on_recv_packet.rs#L40-L44
But the same is not done in `send_transfer`. Since they call the same method for validation and execution, additional checks has to be done to make sure if the denom has trace prefix or not. This is important if the denom is used to derive the escrow account.

## Details

The denom when the packet is sent has `trace_prefix` but when it is received, we dont have `trace_prefix`.

## Solution

Strip the `trace_prefix` in `send_transfer` too.

## Version

0.48.2

**Comment by Farhad-Shabani** [comment]
Hey @dhruvja. I don’t believe we need this. Note that:

Within the **`on_recv_packet`**, we check whether a received packet originated from the IBC modules (whether the receiving chain is the source). If this condition is met, we remove the trace prefix from the token's denom, **as the authentic token name on the receiving chain is the one with the removed `trace_prefix`** and the IBC handlers proceed there with the unescrow using the genuine token’s name.

However, in the **`send_transfer`**, we always use the complete token denomination, including its prefixes, **as it is the exact name of the token on the sender chain**. Therefore, we forward the entire denom to the **`*_coins_validate`** methods. But if a specific use case requires additional checks, there is always this flexibility to incorporate them within those method's implementation.

Additionally, if you're looking to derive an escrow account, it implies that the sender chain is the source. Essentially, you shouldn’t need to strip the `trace_prefix` there.

**Comment by dhruvja** [comment]
I see, that kind of makes sense. Well now i understand the reasoning behind it. Its always better to have the flexibility to remove or preserve it. If i need to remove the trace prefix, i can try to remove it in the validate method so i think we are good. I agree with your reasoning and we can close this issue. Thank you!
