### ISSUE TITLE
Missing some dependency inclusion for feature flags

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#1059]
## Summary

Encountered an issue where essential dependencies for some feature flags were missing in several crates, notably within the `ibc-core`. Surprisingly, the `cargo hack` tool failed to detect these missing dependencies. It sounds like it struggles to accurately assess feature combinations in cases involving multiple layers of crates stacked on top of each other.

## Version

=< 0.50.0

**Comment by romac** [comment]
Maybe give https://crates.io/crates/cargo-hakari a try and see if it works better than cargo-hack?

**Comment by Farhad-Shabani** [comment]
> Maybe give https://crates.io/crates/cargo-hakari a try and see if it works better than cargo-hack?

Appreciate the tip @romac ! I gave `cargo hakari` a try, but it didn't catch the missing dependency either. I even tried running `cargo check` locally with a different set of features, but no luck catching those corner scenarios. Right now, I'm just fixing things manually and sticking with the `cargo hack` since it does catch a bunch of cases.
