### ISSUE TITLE
imp(types): refactor `Default` implementations with concrete names

### ISSUE THREAD

**Issue by rnbguy** [cosmos/ibc-rs#1074]
## Details

There are a few `Default` implementations in ibc-rs codebase. My opinion is - they should not be called `Default`. _Default_ can mean different things in different contexts. Users are encouraged to be specific.

For examples,
- Use concrete [channel order enum](https://github.com/cosmos/ibc-rs/blob/caee889ad308a4aac3f9905de9cdda76c5533cfb/ibc-core/ics04-channel/types/src/channel.rs#L441)
- Use [`Version::empty()`](https://github.com/cosmos/ibc-rs/blob/caee889ad308a4aac3f9905de9cdda76c5533cfb/ibc-core/ics04-channel/types/src/version.rs#L78) directly

My opinion is to use `::zero()`, `::one()`, `::empty()` - to be specific in the context.

Along with it, some of the `Default` values are not expected somewhere else. For example, `CommitmentPrefix` derives `Default`.

https://github.com/cosmos/ibc-rs/blob/caee889ad308a4aac3f9905de9cdda76c5533cfb/ibc-core/ics23-commitment/types/src/commitment.rs#L147-L150

Which recursively used for `Counterparty`'s `Default`.

https://github.com/cosmos/ibc-rs/blob/caee889ad308a4aac3f9905de9cdda76c5533cfb/ibc-core/ics03-connection/types/src/connection.rs#L381-L386

But `CounterParty::try_from(RawCounterParty::from(Counterparty::default()))` fails as `RawCounterparty::from` assigns empty `CommitmentPrefix` - which is not expected when it is converted back to `Counterparty`.

https://github.com/cosmos/ibc-rs/blob/caee889ad308a4aac3f9905de9cdda76c5533cfb/ibc-core/ics03-connection/types/src/connection.rs#L412-L417

## Version

`<= v0.50.0`

**Comment by tropicaldog** [comment]
Hi, can I work on this issue?

**Comment by catconcat** [comment]
Hi, can I work on this issue? @Farhad-Shabani  @rnbguy

**Comment by rnbguy** [comment]
Hey @tropicaldog, you can work on this. 👍🏼 Be mindful to not add any extra helper function or methods. You should just refactor the existing `Default` implementations or `derive`s. 🙏🏼

Also, sorry for my late response. I am not working today. 🧘🏼‍♂️

Nonetheless, Farhad works from PT and I work from CET. If we didn't respond to your messages, please wait for us to come online 🙂
