### ISSUE TITLE
bug(ibc-clients/tendermint): sanity check for `proof_specs` are skipped

### ISSUE THREAD

**Issue by rnbguy** [cosmos/ibc-rs#1100]
## Bug Summary

The `proof_specs` for tendermint client state should validate if they have `min_depth <= max_depth`.

## Details

This is the current `proof_specs` validation.

https://github.com/cosmos/ibc-rs/blob/e048e3400ce5b826b8c6e496fbc54b3a52a2a592/ibc-clients/ics07-tendermint/types/src/client_state.rs#L184-L188

There should be one more check that validates the above inequality. It is best to implement a `validate` method for [`ProofSpecs`](https://github.com/cosmos/ibc-rs/blob/e048e3400ce5b826b8c6e496fbc54b3a52a2a592/ibc-core/ics23-commitment/types/src/specs.rs#L13) that includes all these checks and use it here.

```rs
pub fn validate(&self) -> bool {
  !self.0.is_empty() &&
  self.0.iter().all(|proof_spec| proof_spec.min_depth <= proof_spec.max_depth) 
}
```

## Version

<= 0.50.0

**Comment by gr4yha7** [comment]
@rnbguy i can take this. One question though: what will be the new validation error reason?

**Comment by rnbguy** [comment]
Thanks @gr4yha7 ! you can use

```rs
format!("Depth range in proof-specs cannot be empty: ({}, {})", proof_spec.min_depth, proof_spec.max_depth)
```

Note that my `validate` impl was a reference. Please implement it as following

```rs
fn validate(&self) -> Result<(), Error> {
  if self.0.is_empty() { return Err(...); }
  for proof_spec in &self.0 {
    if proof_spec.min_depth >  proof_spec.max_depth { return Err(...); } 
  }
  Ok(())
}
```

**Comment by gr4yha7** [comment]
@rnbguy I added a PR.
