### ISSUE TITLE
`check-substrate` job fails due to `displaydoc` issue with the latest Rust nightly compiler

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#1105]
## Summary

Context: https://github.com/cosmos/ibc-rs/pull/1099#issuecomment-1964159092

The `check-substrate` job for `no_std` check relies on nightly channel, which fails when running with latest nightly > 2024-02-27 compiler that accepted https://github.com/rust-lang/rust/pull/120393. This should be resolved in https://github.com/yaahc/displaydoc/issues/46.

As a temporary solution, we've set the `NIGHTLY_VERSION` to `nightly-2024-02-24`. It's worthwhile to explore whether it's essential to perform the `no_std` checks on the nightly channel.

**Comment by Manishearth** [comment]
Displaydoc 0.2.5 was published (https://github.com/yaahc/displaydoc/pull/51) which should fix this error.

**Comment by rnbguy** [comment]
Awesome ! Works on latest nightlies :sparkles:
