### ISSUE TITLE
 [ICS23] add conversion checks for `ProofSpec`, `LeafOp`, and `InnerSpec` structs

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#1108]
## Description
Current struct definitions for `ProofSpec`, `LeafOp`, `InnerSpec` lack essential conversion checks between their proto and domain types. This allows e.g. unchecked negative values for `i32` fields.

## Proposal
Define mirror domain types and utilize the **`TryFrom`** trait for robust conversion checks, ensuring type safety

**Comment by catconcat** [comment]
@Farhad-Shabani Hi, could I work on this issue?

**Comment by Farhad-Shabani** [comment]
Hey @tropicaldog, thanks for being up for contributing! Sure, go ahead!
