### ISSUE TITLE
Use macro to auto-generate CosmWasm entrypoints and handle required conversions

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#1169]
## Improvement Summary
Following PR #1167, to make it even simpler to create CosmWasm contracts for implemented light clients, we can write some macros to automate adding the `Context` to the entrypoints, and also generate required conversions for the client and consensus state types shared across CW contract implementations.

**Comment by seanchen1991** [comment]
Closing this issue in favor of #1218
