### ISSUE TITLE
ICS-07 CosmWasm contract build needs CI + Nix flake

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#1170]
## Summary

Following PR #1167:
- Include a CI job to check the ICS-07 CosmWasm contract build
- Add Nix flake to build `ibc_client_tendermint_cw.wasm` file 
   -  This provides Hermes team with a Wasm file aligned with their testing setup

**Comment by rnbguy** [comment]
I decided to go with Github workflow artifacts. It is a native option with less maintenance overhead.

While working on this, I realized we could remove the nix-shell from [`cw-check`](https://github.com/cosmos/ibc-rs/tree/main/ci/cw-check).
