### ISSUE TITLE
bug(ics20): `PrefixedDenom` is parsed with invalid `ChannelId` 

### ISSUE THREAD

**Issue by rnbguy** [cosmos/ibc-rs#1177]
## Bug Summary

Parsing `transfer/channel-75/factory/stars16da2uus9zrsy83h23ur42v3lglg5rmyrpqnju4/dust` to `PrefixedDenom` results in
- `transfer/channel-75/factory/stars16da2uus9zrsy83h23ur42v3lglg5rmyrpqnju4` as `TracePath`
- `dust` as `BaseDenom`

## Details

The parsed data should have:
- `transfer/channel-75` as `TracePath`
- `factory/stars16da2uus9zrsy83h23ur42v3lglg5rmyrpqnju4/dust` as `BaseDenom`

Following [`ibc-go`](https://github.com/cosmos/ibc-go/blob/e2ad31975f2ede592912b86346b5ebf055c9e05f/modules/core/04-channel/types/keys.go#L44), we should validate the `ChannelId`s.

## Version

v0.51.0

## Reference

Fabien Penso [reported](https://twitter.com/fabienpenso/status/1781279208796197020) this.

**Comment by Jaycat66** [comment]
[Holdings_1713235531108.xlsx](https://github.com/cosmos/ibc-rs/files/15079246/Holdings_1713235531108.xlsx)
[Holdings_1713235097135.xlsx](https://github.com/cosmos/ibc-rs/files/15079250/Holdings_1713235097135.xlsx)
