### ISSUE TITLE
ics07: implement `TryFrom<ConsensusState, Error = ClientError>` for `ConsensusStateType`

### ISSUE THREAD

**Issue by rnbguy** [cosmos/ibc-rs#1201]
## Feature Summary

If implemented, we can use `ConsensuState` directly in `ibc-client-tendermint-cw` without a new `AnyConsensusState`.

https://github.com/cosmos/ibc-rs/blob/67d0735d3acc41ddadf8b20eb4b77c02f3707435/ibc-clients/ics07-tendermint/cw-contract/src/client_type.rs#L15-L18

## Proposal

Add the following trait implementation in `ibc-client-tendermint`,

```rs
impl TryFrom<ConsensusState> for ConsensusStateType {
    type Error = ClientError;
    fn try_from(value: ConsensusState) -> Result<Self, Self::Error> {
        Ok(value.0)
    }
}
```

and use `ConsensusState` directly in `ibc-client-tendermint-cw`.

```rs
impl<'a> ClientType<'a> for TendermintClient {
    type ClientState = ClientState;
    type ConsensusState = ConsensusState;
}
```

Note that the `TryFrom<ConsensusState>` never fails. But we can't use `From<ConsensusState>`, as it implies `TryFrom<ConsensusState, Error = Infallible>`. And `ConsensusStateDecoder` requires `TryFrom<ConsensusState, Error = ClientError>`.

https://github.com/cosmos/ibc-rs/blob/67d0735d3acc41ddadf8b20eb4b77c02f3707435/ibc-core/ics02-client/context/src/consensus_state.rs#L11

This is a step towards #1169. Also, refer to #1203 for a discussion about removing the concrete `ClientError` type.

**Comment by rnbguy** [comment]
This will also improve the [rollkit-ibc](https://github.com/cosmos/rollkit-ibc/blob/main/src/types/consensus_state.rs) implementation.

**Comment by seanchen1991** [comment]
Just a note for posterity: we did end up opting for a `From<ConsensusState> for ConsensusStateType` impl, which was enabled after implementing `From<Infallible> for ClientError`.
