### ISSUE TITLE
`MockConsensusState` should not have commitment root

### ISSUE THREAD

**Issue by rnbguy** [cosmos/ibc-rs#1216]
## Improvement Summary

[`mock::ConsensusState` from `ibc_proto`](https://docs.rs/ibc-proto/latest/ibc_proto/ibc/mock/struct.ConsensusState.html) doesn't have any commitment root.

## Proposal

To avoid any unexpected assumptions, we should also remove commitment_root from [`MockConsensuState` in `ibc-testkit`](https://docs.rs/ibc-testkit/latest/ibc_testkit/testapp/ibc/clients/mock/consensus_state/struct.MockConsensusState.html). The [`ConsensusState::root`](https://docs.rs/ibc-testkit/latest/ibc_testkit/testapp/ibc/clients/mock/consensus_state/struct.MockConsensusState.html#method.root) implementation should return a constant value.

Ref: https://github.com/cosmos/ibc-rs/issues/1052#issuecomment-1906675569

**Comment by seanchen1991** [comment]
> The ConsensusState::root implementation should return a constant value.

What should the constant value returned be?

**Comment by rnbguy** [comment]
[The same](https://docs.rs/ibc-testkit/latest/src/ibc_testkit/testapp/ibc/clients/mock/consensus_state.rs.html#23) what we are setting at `ConsensusState::new`: `vec![0]`.

It's a bit difficult to make it `const` as `CommitmentRoot` allocates on heap (has `Vec`) and `ConsensusState::root` returns a reference. We probably need to do something with [`OnceLock`](https://doc.rust-lang.org/std/sync/struct.OnceLock.html) but it requires `std`.

I think, for now, we can just remove the `pub` from `root`:

```diff
  pub struct MockConsensusState {
      pub header: MockHeader,
-     pub root: CommitmentRoot,
+     root: CommitmentRoot,
  }
```

**Comment by seanchen1991** [comment]
Would probably be good to add a note comment about why there exists a private `root` field on `MockConsensusState` when it doesn't exist on the proto. @rnbguy do you have context into why this field was added in the first place?
