### ISSUE TITLE
Update cosmwasm dependencies to v2

### ISSUE THREAD

**Issue by srdtrk** [cosmos/ibc-rs#1242]
## Feature Summary

CosmWasm v2 was released. Currently, it is not possible to use the cosmwasm crates of ibc-rs on projects using CosmWasm v2.

## Proposal

CosmWasm v2 has full backwards compatibility with v1.5. So, it should be as simple as bumping the dependencies.

**Comment by rnbguy** [comment]
Thanks for flagging this. 

> CosmWasm v2 has full backwards compatibility with v1.5.

We had misinformation about the compatibility. Is this something new in the latest versions?

Nonetheless, nothing is blocking at our side. We can totally bump the versions.

**Comment by srdtrk** [comment]
I will verify the compatibility information and get back

**Comment by rnbguy** [comment]
We can probably upgrade 1.5 to 2.0. ([cosmwasm/MIGRATING.md](https://github.com/CosmWasm/cosmwasm/blob/v2.0.3/MIGRATING.md)). I will confirm this with CW team next week.

**Comment by srdtrk** [comment]
Sure. I've talked to CW team in AwesomWasm, they said that there is backwards compatibility unless you use the cosmwasm 2 features. So all should be good

**Comment by webmaster128** [comment]
You can run CosmWasm 2 contracts on 1.5 chains and vice-versa. It has been designed like that from the beginning, see e.g. https://medium.com/cosmwasm/cosmwasm-2-0-bbb94126ce6f. There was just a bug in cosmwasm-std 2.0.0-2.0.3 which prevented that from working for submessage replies but this is now fixed.

**Comment by rnbguy** [comment]
Awesome ! Thanks @webmaster128 for confirming. We can also upgrade the `cw-storage-plus` in that case. :slightly_smiling_face:

**Comment by webmaster128** [comment]
> We can also upgrade the `cw-storage-plus` in that case. 🙂

Yeah there is a version compatible with cosmwasm-std ^2 for sure
