### ISSUE TITLE
MSRV check fails as `derive_more-impl` v1.0.0-beta.6 requires Rust 1.75.0

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#1295]
## Summary
The MSRV check fails ([here](https://github.com/cosmos/ibc-rs/actions/runs/10222932072/job/28288404694?pr=1294)) as `derive_more-impl` v1.0.0-beta.6 requires Rust 1.75.0, while our current MSRV is 1.72.1. This particular version of `derive_more` is pulled in by `cosmwasm-std` since we haven't restricted the patch version.

## Details

```
derive_more-impl v1.0.0-beta.6 (proc-macro)
└── derive_more v1.0.0-beta.6
    └── cosmwasm-std v2.1.0
        ├── cw-storage-plus v2.0.0
        │   └── ibc-client-cw v0.53.0 
        │       ├── ibc-client-tendermint-cw v0.53.0
        │       │   └── tests-integration v0.1.0
        ├── ibc-client-cw v0.53.0
        └── ibc-client-tendermint-cw v0.53.0
        └── tests-integration v0.1.0
```

## Worth Considering
At ibc-rs, we've been aiming to keep the MSRV low for maximum project support, as it's widely used as an upstream dependency. To balance needs, maybe we should consider to separate the workspace of the CosmWasm client implementations from IBC modules. This way, the former can use the latest MSRV, while the latter maintains broader compatibility with a lower MSRV.

**Comment by seanchen1991** [comment]
So would the new directory structure look something like this?
```
ibc-clients
|_cw-workspace        // new workspace that contains the CW dependencies
  |_cw-context
  |_ics07-tendermint  // contains the ics07-tendermint cw contract impl
|_ics07-tendermint
```
Essentially, we've moved `ibc-clients/cw-context` and `ibc-clients/ics07-tendermint/cw-contract` into a separate `ibc-clients/cw-workspace` directory.

**Comment by Farhad-Shabani** [comment]
> So would the new directory structure look something like this?

I'm thinking we should move them up to the root level under a `cosmwasm` directory, right next to the `ibc`. 
It's pretty likely that we'll have CosmWasm contracts for other IBC core/client/app components in the future. Therefore, something like below:

```
ibc-rs/
└── cosmwasm/
    ├── ibc-clients/
    │   ├── cw-context
    │   └── ic07-tendermint
    ├── ibc-apps (later might contain CW contracts)
    ├── ibc-core (later might contain CW contracts)
    ├── Cargo.lock
    └── Cargo.toml (Workspace)
```

**Comment by seanchen1991** [comment]
What existing files need to be moved into `cosmwasm/ibc-apps` and `cosmwasm/ibc-core`?

**Comment by Farhad-Shabani** [comment]
> What existing files need to be moved into `cosmwasm/ibc-apps` and `cosmwasm/ibc-core`?

Ah, those not needed to be created now. Just wanted to demonstrate how directories come together in the end.
