### ISSUE TITLE
Missing check for initial consensus state in create client handler

### ISSUE THREAD

**Issue by hu55a1n1** [cosmos/ibc-rs#13]
## Summary of Bug
The create client handler is not verifying the initial consensus state. Te handler must allow the light client to decide if an initial consensus state is valid and fail otherwise. 

## Version
0.17.0

## Acceptance Criteria
The light client is able to inspect the initial consensus state and fail the handler if it is invalid. 

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by plafer** [comment]
We [now do this](https://github.com/cosmos/ibc-rs/blob/0c5eb875f77f0de3360e58db957e8814aabbee60/crates/ibc/src/core/ics02_client/handler/create_client.rs#L51) right?

**Comment by hu55a1n1** [comment]
Right! This was fixed in https://github.com/informalsystems/ibc-rs/issues/2483.
