### ISSUE TITLE
Cargo.toml has a link to non-existing ibc-client-cw

### ISSUE THREAD

**Issue by vaporif** [cosmos/ibc-rs#1357]
## Bug Summary

It looks like after moving out of the  [CosmWasm workspace](https://github.com/cosmos/ibc-rs/pull/1315) the Cargo.toml file still has a reference to ibc-client-cw, which can be confusing if you're trying to use a patched version of ibc-rs via a commit SHA.

## Details

https://github.com/cosmos/ibc-rs/blob/a1630567d8228920f8251fd110bdbaa07fc29696/Cargo.toml#L88

## Version

v0.55.0

**Comment by rnbguy** [comment]
Thanks for bringing this to our attention. We will publish a patch release soon and also release the `ibc-client-cw` consequently - as the current release breaks it.

**Comment by rnbguy** [comment]
hey @vaporif. Thanks for your patience. 🙏

We made new releases for `ibc-rs` crates (0.55.1) and `ibc-client-cw` (0.55.0). Everything should work now at your end. 🙂
If something broke, please open an issue at [informalsystems/cosmwasm-ibc](https://github.com/informalsystems/cosmwasm-ibc) 🙌
