### ISSUE TITLE
`ConnectionOpenInit` Handler: counterparty connection_id should be hardcoded to `""`

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#169]
[Here](https://github.com/cosmos/ibc-rs/blob/da6653e0716350311d15e6acca08cad625f2d9ff/crates/ibc/src/core/ics03_connection/handler/conn_open_init.rs#L37). The [standard hardcodes](https://github.com/cosmos/ibc/blob/main/spec/core/ics-003-connection-semantics/README.md#opening-handshake) `ConnectionEnd.counterpartyConnectionId` to `""`, and so should we.

**Comment by kevinji** [comment]
@plafer I think this is a dupe of #174.

**Comment by plafer** [comment]
Absolutely is
