### ISSUE TITLE
IcsContext

### ISSUE THREAD

**Issue by ImJeremyHe** [cosmos/ibc-rs#171]
I found that in v0.19.0, this line returns AnyClientState. It is such an obstacle for implementing ICS context in a non-Cosmos-SDK chain.

https://github.com/cosmos/ibc-rs/blob/da6653e0716350311d15e6acca08cad625f2d9ff/crates/ibc/src/core/ics02_client/context.rs#L24

**Comment by hu55a1n1** [comment]
Thank you for reporting this! We have already modified the API to return `Box<dyn ClientState>` now instead of `AnyClientState`. We're planning to have a release with these changes early next week, so that should resolve your issue. :v:
