### ISSUE TITLE
Disallow creation of frozen clients

### ISSUE THREAD

**Issue by hu55a1n1** [cosmos/ibc-rs#178]
## Summary of Bug

We're currently not checking in the create-client handler if the client being created is frozen and I don't think it's in the [spec](https://github.com/cosmos/ibc/tree/main/spec/core/ics-002-client-semantics#create) either. Note the spec requires the [Tendermint client-state to be initialized with a `FrozenHeight: null`](https://github.com/cosmos/ibc/blob/main/spec/client/ics-007-tendermint-client/README.md#client-initialisation), but doesn't enforce this in the handler.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hu55a1n1** [comment]
Related: https://github.com/cosmos/ibc/issues/856

**Comment by plafer** [comment]
ibc-go doesn't do it either, right?

Then I don't think this is a bug, since our current goal is to be "compliant" to ibc-go 5.0.1.
