### ISSUE TITLE
Timestamp define: not be strongly coupled with the time in tendermint

### ISSUE THREAD

**Issue by DaviRain-Su** [cosmos/ibc-rs#180]
## Problem Definition
https://github.com/cosmos/ibc-rs/blob/da6653e0716350311d15e6acca08cad625f2d9ff/crates/ibc/src/timestamp.rs#L25
Can the definition of `timestamp` here not be strongly coupled with the time in `tendermint`.

## Acceptance Criteria

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hu55a1n1** [comment]
We previously used the `chrono` crate but moved away from it (see https://github.com/informalsystems/hermes/issues/1639 and linked issues/PRs for more info). It would be helpful if you could describe your requirements/ideas so we can evaluate potential solutions.

**Comment by DaviRain-Su** [comment]
Thank you for your explanation, this is just my personal understanding, for the third party light client implementation has Time type in the ConsensusState module, I think the third party light-client implementation should not include the type defined in the tendermint. This is my understanding.

**Comment by dzmitry-lahoda** [comment]
So seems fix is cp paste wrapper. And make tendermint into from where needed.   Right?  It will fix ics20 types tendermint dep removed at least.

i am now 816000 bytes, against 819000 contract limit, so i am still ok.
