### ISSUE TITLE
Should Ics20Context implement Module?

### ISSUE THREAD

**Issue by kevinji** [cosmos/ibc-rs#182]
## Summary

Should [Ics20Context](https://docs.rs/ibc/0.19.0/ibc/applications/transfer/context/trait.Ics20Context.html) implement [Module](https://docs.rs/ibc/0.19.0/ibc/core/ics26_routing/context/trait.Module.html) so [ChannelKeeper](https://docs.rs/ibc/0.19.0/ibc/core/ics04_channel/context/trait.ChannelKeeper.html) and [ChannelReader](https://docs.rs/ibc/0.19.0/ibc/core/ics04_channel/context/trait.ChannelReader.html) don't need to be implemented?

## Problem Definition

The current ICS20 logic looks a bit like a standalone IBC module, which means it doesn't interop nicely with the Module system proposed by ICS26. It also leads to a lot of extra boilerplate code due to having to implement ChannelKeeper and ChannelReader that could be delegated to a routing module that implements ICS26.

## Proposal

Have Ics20Context implement Module, and update the interface of Ics20Context so only the [BankKeeper](https://docs.rs/ibc/0.19.0/ibc/applications/transfer/context/trait.BankKeeper.html) and [Ics20Reader](https://docs.rs/ibc/0.19.0/ibc/applications/transfer/context/trait.Ics20Reader.html) functions need to be implemented.

## Acceptance Criteria

The changes proposed are made to Ics20Context and the other related traits.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hu55a1n1** [comment]
Hi @kevinji, the reason `Ics20Context` doesn't implement `Module` is that we didn't want to assume that the struct/component implementing `Ics20Context` is the same as the one implementing `Module`. Both of these are traits, so we could have had `Module`  be a supertrait of `Ics20Context` but that would assume that they're the same type, or we could provide a blanket impl (i.e. `impl<ICS20: Ics20Context> Module for ICS20 { ... }`) but that would be quite a rigid design. The current impl just provides building blocks so people have more flexibility and can implement ICS20 with additional validation if they like. Happy to revisit the design if you think this can be done in a better way.

**Comment by plafer** [comment]
@kevinji can we close this, or do you still see an issue with the current design?

**Comment by kevinji** [comment]
Hey sorry for the late response. I agree that implementing `Module`would require the component implementing `Ics20Context` to implement `Module`, which seems less than ideal.

The use case I was thinking of is that I could separate out the ICS-20 logic into a separate module (possibly separate smart contract). Would this essentially require some way to generate an `Ics20Context` given a `BankKeeper` and `Module` implementation—something like `impl<T: BankKeeper + Module> Ics20Context for T`?

Or, phrased a different way, is there some way to get `ChannelKeeper` and `ChannelReader` for "free" given a `Module` and a `Router`?

**Comment by hu55a1n1** [comment]
Hi @kevinji, I just opened PR #244 - can you take a look and tell us if that addresses your issue?

**Comment by kevinji** [comment]
@hu55a1n1 This looks good, I'll try it out once I get some time to revisit this.
