### ISSUE TITLE
`TendermintClient::verify_upgrade_and_update_state` is not implemented

### ISSUE THREAD

**Issue by romac** [cosmos/ibc-rs#19]
Related to: https://github.com/informalsystems/ibc-rs/issues/722

## Summary

The `TendermintClient::verify_upgrade_and_update_state` is currently not implemented, even though it is called in the UpgradeClient handler.

https://github.com/informalsystems/ibc-rs/blob/efbf7d18512fe6efcb593de68735b7f8783fd652/modules/src/clients/ics07_tendermint/client_def.rs#L395-L403

https://github.com/informalsystems/ibc-rs/blob/efbf7d18512fe6efcb593de68735b7f8783fd652/modules/src/core/ics02_client/handler/upgrade_client.rs#L52-L57
## Problem Definition

The UpgradeClient is therefore non-functional at the moment, as it will panic once the method is called.

## Proposal

Implement the `verify_upgrade_and_update_state` method for `TendermintClient`.

## Acceptance Criteria

The `verify_upgrade_and_update_state` is implemented in `TendermintClient`, and its behavior is captured in a test for the UpgradeClient handler.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by plafer** [comment]
Until we know how to implement this properly, we should return an `Error` instead of crashing (either at the tendermint light client level, or even at the core handler level).

Related: #141
