### ISSUE TITLE
Proc macro attr for event attributes

### ISSUE THREAD

**Issue by hu55a1n1** [cosmos/ibc-rs#214]
## Summary

Would be nice to have a proc macro attr for event attributes -> 
```rust
#[abci_tag(PORT_ID_ATTRIBUTE_KEY)]
pub struct PortIdAttribute {
    pub port_id: PortId,
}
```
The generated code would be -> 
```rust
pub struct PortIdAttribute {
    pub port_id: PortId,
}

impl From<PortIdAttribute> for Tag {
    fn from(attr: PortIdAttribute) -> Self {
        Tag {
            key: PORT_ID_ATTRIBUTE_KEY.parse().unwrap(),
            value: attr.port_id.to_string().parse().unwrap(),
        }
    }
}
```

-> [Original comment on #198](https://github.com/cosmos/ibc-rs/pull/198#discussion_r1012317911)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by DaviRain-Su** [comment]
seem we should use derive marco with attribute, this link https://doc.rust-lang.org/reference/procedural-macros.html#derive-macro-helper-attributes

**Comment by plafer** [comment]
Will not implement as this was found to be overkill in #276.
