### ISSUE TITLE
 Change host_height, host_timestamp return value to a Result in ClientReader, ConnectionReader, ChannelReader and ValidationContext

### ISSUE THREAD

**Issue by DaviRain-Su** [cosmos/ibc-rs#242]
## Summary

For downstream implementation of `ibc-rs` interface, `host_height`, `host_timestamp` may be wrong, here we suggest to return a Result type.

## Acceptance Criteria

change before is 
```rust
fn host_height(&self) -> Height;
fn host_timestamp(&self) -> Timestamp;
```
change after is 
```rust
fn host_height(&self) -> Result<Height, Error>;
fn host_timestamp(&self) -> Result<Timestamp, Error>;
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by plafer** [comment]
Could you provide an example scenario where it would be the case that the host cannot provide either its height or timestamp?

**Comment by DaviRain-Su** [comment]
> Could you provide an example scenario where it would be the case that the host cannot provide either its height or timestamp?

For downstream implementers to construct Height and timestap here there is a Result type, for the construction of Height returns a Result, my suggestion is that the host_height function returns a Return type of Result. For host_timestamp is similar.

https://github.com/octopus-network/substrate-ibc/blob/6d49011521414b167f05d54bf586a825be4d9a5f/src/module/core/ics02_client.rs#L292
