### ISSUE TITLE
Rename `Ics*` names to something more descriptive

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#245]
We use this pattern a lot in the codebase, and I think we should move away from it. For example, `Ics20Context` could be renamed to `TransferContext`.

**Comment by DaviRain-Su** [comment]
This enhancement can be assigned to me

**Comment by plafer** [comment]
Thanks!

**Comment by DaviRain-Su** [comment]
`Ics26Context` Rename to `RoutingContext`?

**Comment by plafer** [comment]
I would be more in favor of `RouterContext`, but we can discuss this further on the PR itself
