### ISSUE TITLE
Make `ValidationContext` and `ExecutionContext` use non-core `Error` types

### ISSUE THREAD

**Issue by DaviRain-Su** [cosmos/ibc-rs#269]
Originally comes out of [discussion](https://github.com/cosmos/ibc-rs/pull/255#issuecomment-1325805412)

Currently, our methods in our `Context` traits return the `Error` types that are used by our handlers. We should create new `Error` types for methods in the `Context` traits. This will  allow us to remove error variants that are only meant to be used by hosts (e.g. [this](https://github.com/cosmos/ibc-rs/blob/42b54613ba5c81b49557a8be46af517eec0b2fce/crates/ibc/src/core/ics04_channel/error.rs#L21)).
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by plafer** [comment]
This is now a duplicate of #270
