### ISSUE TITLE
Release v0.24.1

### ISSUE THREAD

**Issue by hu55a1n1** [cosmos/ibc-rs#294]
# Release IBC-RS  v0.24.1

⚡

- [ ] Create a new release in the changelog, using [`unclog`](https://github.com/informalsystems/unclog).
  - If doing a release candidate (`rc`) version, then skip the `unclog release` step.
- [ ] Bump all crate versions to the new version.
- [ ] Reassign unfinished issues of previous milestone to the next milestone.

**Note**: \<placeholder-issue\>

**Comment by plafer** [comment]
We will release v0.25.0 directly instead
