### ISSUE TITLE
Implement ICS 721: NFT transfer on `ibc-rs`

### ISSUE THREAD

**Issue by blasrodri** [cosmos/ibc-rs#346]
## Summary

Implement iCS 721: NFT transfer on `ibc-rs`

## Problem Definition

At Composable, we are currently finishing up our Centauri Bridge, which will connect the Polkadot with Cosmos. It is important
for us to be able to support NFT transfers to give those chains that are using this feature through IBC.

## Proposal

Ideally follow the [spec](https://github.com/cosmos/ibc/blob/main/spec/app/ics-721-nft-transfer/README.md) and the [reference implementation written in go](https://github.com/bianjieai/nft-transfer), and a [reference implementation in CosmWasm](https://github.com/public-awesome/ics721)

### Happy path
NFT being transferred from chain A to B, and then back from B to A.

### Less happy path
NFT transfer timing out, and not being transferred to chain B from A.
NFT transfer succeeding from A to B, but timing out from B to A.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by plafer** [comment]
Thank you for opening this issue. Would someone from Composable have the capacity to implement this? Ideally, we would also have a (brief) ADR outlining the architecture of the module so that we can agree on the general architecture before you start implementing.

Also please note that with #322, the [`Module` API](https://github.com/cosmos/ibc-rs/blob/4b293327a2cceafb1986d59b6b24769063003413/crates/ibc/src/core/ics26_routing/context.rs#L112) will be changed slightly. However the merge conflicts shouldn't be that bad (depending on when you start implementing).

**Comment by blasrodri** [comment]
> Thank you for opening this issue. Would someone from Composable have the capacity to implement this? Ideally, we would also have a (brief) ADR outlining the architecture of the module so that we can agree on the general architecture before you start implementing.
> 
> Also please note that with #322, the [`Module` API](https://github.com/cosmos/ibc-rs/blob/4b293327a2cceafb1986d59b6b24769063003413/crates/ibc/src/core/ics26_routing/context.rs#L112) will be changed slightly. However the merge conflicts shouldn't be that bad (depending on when you start implementing).

Pleasure :)

Our goal is to do the bulk of the work, and get from the core maintainers support on the review side + architecture. We'd have to port these changes into our own fork, since we aren't currently using the canonical `ibc-rs`. But I felt it was a good feature to collaborate and potentially avoid duplication of efforts.

What do you think?

**Comment by plafer** [comment]
Yes that sounds great to me 😀

**Comment by blasrodri** [comment]
I'd like to know what's your opinion on https://github.com/public-awesome/ics721
We could potentially leverage most of the work here
