### ISSUE TITLE
`{ChannelReader,ValidationContext}::hash()` must not be abstract

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#375]
This `hash()` function is used in both [packet commitments](https://github.com/cosmos/ibc-rs/blob/06abed0085e6c001764ee759e04a44512bfb6fe9/crates/ibc/src/core/context.rs#L338-L356) and [acknowledgement commitments](https://github.com/cosmos/ibc-rs/blob/06abed0085e6c001764ee759e04a44512bfb6fe9/crates/ibc/src/core/context.rs#L358-L360). If the host chooses to use anything other than SHA256 (see [ibc-go](https://github.com/cosmos/ibc-go/blob/aed382b1d9ff212de8036caeda9bac1a08b41ad2/modules/core/04-channel/types/packet.go#L19-L41)), it will break the Merkle proofs of the IBC provable store.

We should instead enforce this hash function by giving it a default implementation (or even remove it from the trait).

**Comment by Farhad-Shabani** [comment]
Addressed in #492
