### ISSUE TITLE
Remove `ChannelEnd::order_matches()`

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#394]
We should use a `match` statement instead. This pattern encourages not looking at all possible variants, and shouldn't be used.

At the same time, we should understand what the `Order::None` represents, and if we keep it, what to do in cases where the order is `None`.

**Comment by DaviRain-Su** [comment]
I think is ok, maybe can implement to seem this.
```rust
  pub fn order_matches(&self, other: &Order) -> bool {
        // self.ordering.eq(other)
        match (self.ordering, other) {
            (Order::None, Order::None) => true,
            (Order::Unordered, Order::Unordered) => true,
            (Order::Ordered, Order::Ordered) => true,
            _ => false,
        }
   }
```

**Comment by DaviRain-Su** [comment]
<img width="1091" alt="截屏2023-06-01 17 20 56" src="https://github.com/cosmos/ibc-rs/assets/53282030/eed35db1-8f22-4e82-aeae-ef5d8f33657b">

Just search `order_matches()`, for now, pass param values is Order. We don't used any field.
