### ISSUE TITLE
Add needed unit or integration tests for Tendermint proof verifications 

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#398]
## Summary

There is a need to cover Tendermint proof verifications with proper tests after issue #396.
Mock Chain passes the proof verifications and we are not able to catch Tendermint-specific errors with the existing tests. 

## To Do

To ensure Tendermint proof verifications are correctly executed, we should add corresponding unit tests or somehow integrate `basecoin-rs` into our CI process

Blocked on: #677

**Comment by plafer** [comment]
#396 was a core IBC bug; not Tendermint-specific. Did you mean "core handler validation needs to be tested" instead of "Tendermint proof verifications"?

**Comment by Farhad-Shabani** [comment]
It occurred in the core section, but catching such errors needs that tests go through a proof verification process (e.g. [here](https://github.com/cosmos/ibc-rs/blob/2b8d1c5dcb9969609f3216578af672ae9c292a7f/crates/ibc/src/core/ics04_channel/handler/chan_open_confirm.rs#L173-L185)), which is a client-specific action. So, we can match the output with the fed test data.
Note that we already bypass this check for `MockClientState` by setting the result of such methods to `Ok()` (e.g. [here](https://github.com/cosmos/ibc-rs/blob/2b8d1c5dcb9969609f3216578af672ae9c292a7f/crates/ibc/src/mock/client_state.rs#L350-L361))

**Comment by plafer** [comment]
Ah I see; yes that's right.

**Comment by rnbguy** [comment]
closed by #1109
