### ISSUE TITLE
Convert tests to use `rstest` crate

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#426]
We should move towards using `rstest` crate to make tests more easily readable and maintainable.

**Comment by Farhad-Shabani** [comment]
Would be great, if you could provide a bit more context around this crate (for reference) and the benefits it brings compared to the current approach?
wouldn't it be better to rely on crates that are mostly maintained by organizations rather than individual contributors?

**Comment by plafer** [comment]
I was looking for a crate that provided basic helpers for unit tests; mainly setup/teardown functions. `rstest` is the only one I found, and had the features I needed.

> wouldn't it be better to rely on crates that are mostly maintained by organizations rather than individual contributors?

This is a very simple crate that provides helpers for tests. Thus there's no risk of, say, security vulnerabilities that remain un-patched and affect our core software.

> the benefits it brings compared to the current approach

The current way we do tests is very rigid: all tests run the same checks, so it's hard to just add new tests that want to test different things. Additionally, a little benefit of the new approach is that we'll see how many tests we actually have (the current approach lumps a bunch into one so we don't know how many tests we have).

**Comment by Farhad-Shabani** [comment]
Yeah, there doesn't seem to be a better option. Thanks for letting me know :pray:

**Comment by plafer** [comment]
Closing; given @Farhad-Shabani's comments it's not clear that we need to use `rstest`.
