### ISSUE TITLE
Define testing strategy

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#433]
We need to define a testing strategy that will identify *what needs to be tested* along with *how to test it*. For example, some questions to answer include

- Currently `MockContext` doesn't do proper proofs. Should it? This would involve modifying the store to be a Merkle tree.
- We want to make sure that we are compatible with `gaia`. However, integration tests of that sort are very slow, so we probably don't want to run them on every PR. Perhaps before every release is sufficient?
- What will we be testing with basecoin-rs, that won't be covered with the `MockContext`-based tests?

Perhaps the outcome of this issue is an ADR which answers all these questions.

**Comment by adizere** [comment]
There's an ADR linked from https://github.com/cosmos/ibc-rs/pull/1109 that closes this issue.

**Comment by adizere** [comment]
We have not answered the third question in the original issue description:

> What will we be testing with basecoin-rs, that won't be covered with the MockContext-based tests?

This is subject for future work.
