### ISSUE TITLE
`ValidationContext::compute_packet_commitment` should be a standalone exported function

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#470]
There's only one correct way to compute a commitment. This would also make it available for implementors e.g. of `TokenTransferValidationContext`.

**Comment by Farhad-Shabani** [comment]
When you say "_one correct way_", do you mean it's required by the protocol? Wouldn't be a different implementation for a non-tendermint chain? 
If that's the case, I think it would make sense to apply this to the [`ack_commitment()`](https://github.com/cosmos/ibc-rs/blob/a19cc8013a9ab88e0dac986f9bcf3156bbb95548/crates/ibc/src/core/context.rs#L374) method as well.

**Comment by plafer** [comment]
> When you say "one correct way", do you mean it's required by the protocol?

Yes; if a chain computes it differently from any other chain, the Merkle proof for checking that the packet commitment is there will fail. This is independent from the host consensus algorithm.

> If that's the case, I think it would make sense to apply this to the [ack_commitment()](https://github.com/cosmos/ibc-rs/blob/a19cc8013a9ab88e0dac986f9bcf3156bbb95548/crates/ibc/src/core/context.rs#L374) method as well.

Right, we should also export it as standalone. Related: #375
