### ISSUE TITLE
Missing `store_connection_channels` after `ExecutionContext` refactor

### ISSUE THREAD

**Issue by kevinji** [cosmos/ibc-rs#479]
## Bug Summary

The function
```rust
fn store_connection_channels(
    &mut self,
    connection_id: ConnectionId,
    port_id: PortId,
    channel_id: ChannelId,
) -> Result<(), ContextError>;
```
got removed during the `ExecutionContext` refactor, but 
```rust
fn connection_channels(
    &self,
    connection_id: &ConnectionId,
) -> Result<Vec<(PortId, ChannelId)>, ContextError>;
```
remains in `ValidationContext`.

## Details

Since `store_connection_channels` got removed from `ExecutionContext`, I think there isn't a function any more that ties connections to (port, channel) pairs anymore, meaning `connection_channels` would always return an error.

## Version

ibc-rs v0.29.0 onwards.

**Comment by Farhad-Shabani** [comment]
It can still be retrieved by querying for all channels using `ChannelEndPath` and matching the passed `connection_id` with the `connection_hops` field of each found `ChannelEnd`. (like [here](https://github.com/informalsystems/basecoin-rs/blob/d436b310872b5013d1fc5138604fee4f3c1109bc/src/app/modules/ibc.rs#L1760-L1763) in basecoin-rs).
Though indeed, it is not an efficient way and in some implementations can end up with the error.

**Comment by plafer** [comment]
I think the main point though is that it is no longer used by the core handlers, and so serves no purpose. So IIUC, we should just remove `ValidationContext::connection_channels()`.
