### ISSUE TITLE
Add `From<Amount>` conversion for `u64`

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#486]
## Summary

Improve user experience around `struct Amount(U256)` by adding an additional conversion helper method `From<Amount>` for `u64`

**Comment by kevinji** [comment]
Maybe a silly question but won't calling `amount.into()` panic if `amount` is bigger than a `u64` but smaller than a `U256`?

**Comment by plafer** [comment]
Oh yes you're right, I totally missed that! We'll fix this right away.
