### ISSUE TITLE
Remove `'static` requirement on `Module`

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#490]
Implicitly through `AsAnyMut`

**Comment by romac** [comment]
Can you expand a bit on why this is needed?

**Comment by plafer** [comment]
It was requested by Namada ([see their `Context` object](https://github.com/anoma/namada/blob/565f985bd31cf51f76261cafdf45b3837fad76ce/shared/src/ledger/native_vp/mod.rs#L54) they want to implement `Module` for). And I find this to be a good change in general as it gives more flexibility to implementors, without many drawbacks (if any?) for us.
