### ISSUE TITLE
Remove `Router::has_route`

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#503]
We currently use `has_route()` in `ExecutionContext::execute()`, but `has_route()` typically is implemented as 

```rust
fn has_route(&self, module_id: &ModuleId) -> bool {
    self.get_route(module_id).is_some()
}
```

However, `get_route()` (immutable) success doesn't imply `get_route_mut()` (mutable) will succeed. Our [`has_route()` call](https://github.com/cosmos/ibc-rs/blob/80f751666a9e155195d27b3295a6b62df65232ed/crates/ibc/src/core/context.rs#L192) is redundant with the [later calls](https://github.com/cosmos/ibc-rs/blob/25db45c6caf1f6037f7b214c5f900b76e26aac9b/crates/ibc/src/core/context/chan_open_init.rs#L27-L29) to `get_route()` anyways.

**Comment by PanGan21** [comment]
Hey @plafer i hope pr #740 is what is meaning to be done in this issue. If I misunderstood it please let me know.
