### ISSUE TITLE
[Transfer App] Return Result instead of boolean for `is_send_enabled` and `is_receive_enabled‍‍` methods

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#508]
## Problem Definition

The `is_send_enabled` and `is_receive_enabled` methods under the `TokenTransferValidationContext` return a boolean value whose sole purpose is to propagate errors. This violates Rust's error-handling convention of using the Result type for error reporting.
This implementation was suitable as long as no specific error reporting was required, but it can become an issue as our codebase grow and require more detailed error reporting.

**Comment by plafer** [comment]
> whose sole purpose is to propagate errors.

can you expand on that? IMO, the purpose is to [fail the transfer](https://github.com/cosmos/ibc-rs/blob/d0d0683e9257fd83ef2e00897b29adf5e8445072/crates/ibc/src/applications/transfer/relay/send_transfer.rs#L35-L37) if for any reason the hosts wants to freeze transfers. In other words, it's sort of a "kill switch" on transfers.

**Comment by Farhad-Shabani** [comment]
> can you expand on that? IMO, the purpose is to [fail the transfer](https://github.com/cosmos/ibc-rs/blob/d0d0683e9257fd83ef2e00897b29adf5e8445072/crates/ibc/src/applications/transfer/relay/send_transfer.rs#L35-L37) if for any reason the hosts want to freeze transfers. In other words, it's sort of a "kill switch" on transfers.

Indeed, it is. What I meant:
- It's actually uncommon to use a `boolean` as a return type instead of `Result` to handle failures. In our case, we return a `boolean` and just afterward use it to handle failures. Why not just fail right away?
- Also, this way implementors have more control over the message of propagated error and can keep it consistent with their own project
