### ISSUE TITLE
[Crate] Pass `ChannelId` by value instead of reference since it impls `Copy`

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#537]
## Summary

Part of #25, originated from https://github.com/informalsystems/hermes/pull/2071#discussion_r845063824

We should revisit the codebase and check wherever this comment applies pass the `ChannelId` by value instead of getting the reference since it impls the `Copy`

**Comment by plafer** [comment]
See https://github.com/cosmos/ibc-rs/pull/542#discussion_r1144928669
