### ISSUE TITLE
[ICS24] Discard `Default` impl for `ClientId` and move away from `tm_client_type` in unit tests 

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#552]
## Problem Statement

Part of #373

Since `ClientId` serves a wider range of chains, it does not make sense to have a [default](https://github.com/cosmos/ibc-rs/blob/b807d8f6335a7105762a9cb8f753320c13d1652c/crates/ibc/src/core/ics24_host/identifier.rs#L240-L244) value. As such, we should also get our unit tests client-indifference and discard `tm_client_type` calls

**Comment by plafer** [comment]
Note that our current unit tests have no proof verifications, so even having different client names wouldn't catch bugs like #551. For now, I made sure that [our integration tests](https://github.com/informalsystems/basecoin-rs/pull/87) use different client names.

still a good improvement to have though in the long term.

**Comment by Farhad-Shabani** [comment]
Definitely. This one caught my eye again while fixing tests for #531. 
Unit tests mainly use the `MockCotext` but having `tm_client_type` imported, we circumvent the mock in some places
