### ISSUE TITLE
Emit "message" event for IBC relayer

### ISSUE THREAD

**Issue by yito88** [cosmos/ibc-rs#563]
## Bug Summary
Each handler should emit also "message" event for IBC relayer according to https://github.com/cosmos/ibc-go/blob/main/docs/ibc/events.md

## Details
In Namada testing, after executing sending a token, Hermes wasn't notified because the message event wasn't emitted.
https://github.com/cosmos/ibc-rs/blob/2d64819d7ff8ce770d2351b92588b06f4fc5ec30/crates/ibc/src/core/ics04_channel/handler/send_packet.rs#L124

Hermes' monitor subscribes to the IBC-specific events with `message.module`.
https://github.com/informalsystems/hermes/blob/a285c015c604819b213c1582d901e5ef140d3f47/crates/relayer/src/event/monitor.rs#L147-L165

## Version
0.32.0

**Comment by plafer** [comment]
Interesting, when implementing https://github.com/cosmos/ibc-rs/issues/137, I had initially added this event, but then removed in after I realized that it was an "internal event" for SDK chains (used internally to route the event or something). I'm surprised that hermes needs it; let me look into that.

**Comment by plafer** [comment]
Agreed, let's emit these events too, as hermes does indeed rely on them for relaying.

Opened https://github.com/informalsystems/hermes/issues/3190 so that hopefully we can remove them at some point is the future.
