### ISSUE TITLE
Find some miss match, in ics07 updatestate

### ISSUE THREAD

**Issue by DaviRain-Su** [cosmos/ibc-rs#565]
## Bug Summary

https://github.com/cosmos/ibc-rs/blob/8d5178d0cdc0329fa89f5050807b8aa0290f64a2/crates/ibc/src/clients/ics07_tendermint/client_state.rs#L455 
ibc-rs use header height to get consensus_state, but in ibc-go use clientState height to get consensus_state.
https://github.com/cosmos/ibc-go/blob/92ad328f8e811f4c4abc8194fd228731072f8b12/modules/light-clients/07-tendermint/proposal_handle.go#L49

**Comment by plafer** [comment]
The ibc-go line that you reference is in the `CheckSubstituteAndUpdateState()` function, which is something else. [This](https://github.com/cosmos/ibc-go/blob/3cf08aa2f9694fbd4e3dc3c8bfa8f8b202495b05/modules/light-clients/07-tendermint/update.go#L49) is the  analogous line in ibc-go, which also uses the header height.

However I'm now noticing that we use the `Header::signed_header.header.height` field, whereas ibc-go uses the `Header::TrustedHeight` field. I'll look into that

EDIT: we do check that these 2 values be the same [here](https://github.com/cosmos/ibc-rs/blob/8d5178d0cdc0329fa89f5050807b8aa0290f64a2/crates/ibc/src/clients/ics07_tendermint/header.rs#L151-L156). I'd still like to know why we don't just use `Header::TrustedHeight` directly.

**Comment by plafer** [comment]
> [This](https://github.com/cosmos/ibc-go/blob/3cf08aa2f9694fbd4e3dc3c8bfa8f8b202495b05/modules/light-clients/07-tendermint/update.go#L49) is the analogous line in ibc-go, which also uses the header height.

This is wrong. The line I reference here is just part of an optimization that we do in ibc-rs that ibc-go doesn't do: if the header to update was already installed, then [we skip](https://github.com/cosmos/ibc-rs/blob/8d5178d0cdc0329fa89f5050807b8aa0290f64a2/crates/ibc/src/clients/ics07_tendermint/client_state.rs#L461-L467) the rest of the verification.

The correct analogous line is [this one](https://github.com/cosmos/ibc-rs/blob/8d5178d0cdc0329fa89f5050807b8aa0290f64a2/crates/ibc/src/clients/ics07_tendermint/client_state.rs#L474-L475). This checks out with ibc-go; we also use the trusted height.

> EDIT: we do check that these 2 values be the same [here](https://github.com/cosmos/ibc-rs/blob/8d5178d0cdc0329fa89f5050807b8aa0290f64a2/crates/ibc/src/clients/ics07_tendermint/header.rs#L151-L156). I'd still like to know why we don't just use Header::TrustedHeight directly.

This was also wrong, only the revision number is checked to be the same, which makes sense (we ensure that the previously installed header, at height `trusted_height`, has the same revision number as the header we're attempting to install.

All this being said, there does not appear to be any issue with our implementation there.
