### ISSUE TITLE
`ClientState::validate_proof_height` is unused

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#606]
It is only used in tests. I believe we can just remove it from `ClientState`.

**Comment by Farhad-Shabani** [comment]
Closing as the `validate_proof_height` in most ibc-rs handlers already is a validation step (like [here](https://github.com/cosmos/ibc-rs/blob/ac579fa35029c6176c57ba3c629490f18a5043e4/ibc-core/ics03-connection/src/handler/conn_open_ack.rs#L72)).
