### ISSUE TITLE
Tendermint light client: update misbehaviour handling

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#616]
tendermint-rs's light client does an extra check that should be removed in `ProdVerifier::verify()`, that we call in `ClientState::verify_client_message()`. We are currently blocked on tendermint-rs providing a new API that we can use.

Context: https://github.com/cosmos/ibc-rs/pull/584#discussion_r1160711722
Blocked on: https://github.com/informalsystems/tendermint-rs/issues/1294

**Comment by Farhad-Shabani** [comment]
Did we accomplish this in #700 ([here](https://github.com/cosmos/ibc-rs/pull/700/files#diff-078f77df0b41c28ab6a620832c78efe46c8f28a5f9ad41c0c4c75a121eb9635aR90))?

**Comment by plafer** [comment]
Yep!
