### ISSUE TITLE
Remove `Header` trait

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#617]
The [`Header`](https://github.com/cosmos/ibc-rs/blob/707d032dac76c3e4b2c70a9dd4c508d03d67d62a/crates/ibc/src/core/ics02_client/header.rs#L19) trait is only used in tests, and doesn't serve a clear purpose. We should remove it.

**Comment by DaviRain-Su** [comment]
In ibc-go use ClientMessage to Update ClientState, replace Header.
