### ISSUE TITLE
[ICS03][ICS04] Refactor and fix version validation in connection and channel handshakes

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#625]
## Summary

Part of #233

Found confusing validation codebase around `Version` type, in particular in places we call `contains()` and **unsure if checks are done correctly**. Also, there is a bit higher processing cost within `pick_version` method.
Streamlining and maintaining the code will ensure all validation steps are completed.

**Comment by plafer** [comment]
Our [version check](https://github.com/cosmos/ibc-rs/blob/87f2f540c96f9bd3d12ea2a459e541732c92189e/crates/ibc/src/core/ics03_connection/handler/conn_open_ack.rs#L49) in connection handshakes is incorrect. See proper algorithm in [ibc-go](https://github.com/cosmos/ibc-go/blob/295bab01f633633e0d6136ba9b974c0e248edbe5/modules/core/03-connection/keeper/handshake.go#L29).
