### ISSUE TITLE
`MsgUpdateClient` domain type does not faithfully represent the IBC protocol messages

### ISSUE THREAD

**Issue by hdevalence** [cosmos/ibc-rs#628]
## Bug Summary

#584 broke the representation of IBC protocol messages, by creating a single domain type, `MsgUpdateClient`, that represents multiple IBC protocol messages (both `MsgUpdateClient` and `MsgSubmitMisbehavior`).

The domain types should faithfully represent the IBC protocol messages, rather than forcing downstream clients to re-parse them to figure out what message they actually got.

This also breaks the use of the `ibc_proto` traits, forcing callers to write code like
```rust
let msg = <MsgUpdateClient as ibc_proto::protobuf::Protobuf<
    ibc_proto::ibc::core::client::v1::MsgUpdateClient,
>>::decode(raw_action_bytes)?;
```
or
```rust
<ibc::core::ics02_client::msgs::update_client::MsgUpdateClient as Protobuf<
    ibc_proto::ibc::core::client::v1::MsgUpdateClient,
>>::encode_vec(&msg)
```
just to encode or decode messages.

**Comment by plafer** [comment]
Thank you for bringing this up; I think I found a way to not break them in this way and still implement ibc-go's ADR 6 (our original intent). Will submit a PR soon
