### ISSUE TITLE
Bump ics23 to v0.10 to get `prehash_key_before_comparison`

### ISSUE THREAD

**Issue by kevinji** [cosmos/ibc-rs#640]
## Feature Summary

ics23 v0.10 includes cosmos/ics23#136 which is needed for certain Merkle tree implementations. We would like to pick this up, but I think this is blocked on ibc-proto-rs getting the `prehash_key_before_comparison` field in `ibc_proto::ics23::ProofSpec`.

Fixing cosmos/ibc-proto-rs#10 would make it easier to pick up upstream ics23 changes.

## Proposal

Bump ics23 to v0.10 after making the needed changes in ibc-proto-rs.

**Comment by romac** [comment]
I am working on https://github.com/cosmos/ibc-proto-rs/issues/10, will keep you posted.

**Comment by romac** [comment]
I opened a draft PR in ibc-proto-rs: https://github.com/cosmos/ibc-proto-rs/pull/92

Currently blocked on getting this in `ics23`: https://github.com/cosmos/ics23/pull/145

**Comment by romac** [comment]
It's out: https://github.com/cosmos/ibc-proto-rs/releases/tag/v0.31.0-alpha.1

**Comment by plafer** [comment]
We can't quite upgrade yet because it depends on tendermint-proto v0.31.0, but tower-abci only supports v0.30.0 at the moment (which most of our users use)
