### ISSUE TITLE
 Implement an Ics06 SoloMachine client

### ISSUE THREAD

**Issue by DaviRain-Su** [cosmos/ibc-rs#641]
## Feature Summary

 Implement an Ics06 SoloMachine client.

link: https://github.com/cosmos/ibc-go/tree/main/modules/light-clients/06-solomachine

## Proposal

you can assign me the task and I will complete the requirement.

**Comment by Farhad-Shabani** [comment]
Thanks for initiating this! Really appreciate you wanted to contribute 🙏🏻 
Just wanted to let you know, we have a lot on our plate this quarter, and got a bunch of stuff going on. SoloMachine isn’t a top priority at the moment, unless there is an immediate need. 
Anyhow, we can do our best to review the relevant PRs, in a timely manner though. I hope it won’t get you frustrated :)
Perhaps, to make things easier for everyone, it would be cool to break down the implementation into smaller chunks/PRs and work on a separate feature branch. This way, we can review and merge your changes without slowing down each other. 
Let us know what you think.

**Comment by DaviRain-Su** [comment]
Now I have roughly implemented the ICS06 solomachine client, and the current version is aligned with ibc-go  ics06-solomachine client proto v3 version. link: https://github.com/octopus-network/ics06-solomachine
