### ISSUE TITLE
Move `Header` trait under `mocks`

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#715]
Currently, the [`Header` trait](https://github.com/cosmos/ibc-rs/blob/2403dc3cef595454cf0629cfe15dcd8b176f56a9/crates/ibc/src/core/ics02_client/header.rs#L21) is only used in tests. Hence, we should move it somewhere under the `mocks` module.

**Comment by Farhad-Shabani** [comment]
Does it differ from #617 ?

**Comment by plafer** [comment]
Hmm, no not really. I'm not sure if it's better to remove or move to tests only, but we can figure it out when we work on the issue. Closing
