### ISSUE TITLE
Move transfer application and tendermint client to separate crates

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#716]
We should move the `transfer` application and the `tendermint` client to separate crates. This way, these can evolve independently from the core ibc-rs. 

Notably, post ibc-rs 1.0, this will mean that if needed we will be able to make breaking changes to the app or client (incrementing the major version) without needing to increment ibc-rs's major version. This will completely decouple core IBC from Tendermint.

**Comment by DaviRain-Su** [comment]
i can do this.

**Comment by plafer** [comment]
Thank you! However, let's hold it for now (I should have marked it as blocked). Currently our tests depend on the `tendermint` client, and we don't want `ibc-rs` to depend on the future `tendermint` client crate. And currently, our `Mock*` types are not test-only; if they were, we could simply import the tendermint client crate as a `dev-dependency`.

@rnbguy is currently re-architecting our tests (#677), so let's wait until this direction is more clear before we move forward with this issue.
