### ISSUE TITLE
Enhance abstraction of Acknowledgement result to get accessible by all IBC apps

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#717]
## Background
For every IBC application on the module callback, especially during the `on_recv_packet` process, there can be an acknowledgment result (either a success or an error). Currently, we use `TokenTransferAcknowledgement` enum specifically for the ICS20. To avoid redundancy and looking at the places and how IBC-go handles the [`Acknowledgment`](https://github.com/cosmos/ibc-go/blob/ba62612a490436e0cb948f6421e0e838b9a277ea/modules/core/04-channel/types/channel.pb.go#L402-L409), it is recommended to generalize this abstraction and place it under the `ics04_channel` section, making it accessible for any application.

This is necessary for the ICS27 implementation.

**Comment by plafer** [comment]
> This is necessary for the ICS27 implementation.

Can you explain why? Does ICS27 rely on a particular structure of the `Acknowledgement`?
