### ISSUE TITLE
Explore initiatives to expand IBC out of Cosmos

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#727]
## Background

This issue tracks our investigations we’ve got planned for the 3rd quarter of 2023. We’ll be exploring initiatives to expand IBC out of Cosmos, with the goal of informing the direction of IBC-rs. We will document our findings either through blog posts, ADRs, or whichever format ends up being most appropriate.

**Comment by DaviRain-Su** [comment]
This project plans to use IBC as a bridge. https://www.sovereign.xyz/

**Comment by Farhad-Shabani** [comment]
We achieved this objective mainly by upstreaming the knowledge we gained from the Sovereign IBC integration project into the ibc-rs. In particular, that work played a significant role in preparing and implementing ADR09 and ADR10.
