### ISSUE TITLE
[ICS02] Design flaw of `verify_upgrade_client` function of `ClientState` trait

### ISSUE THREAD

**Issue by riversyang** [cosmos/ibc-rs#739]
## Problem Statement

While implementing [ICS12 (client for NEAR protocol)](https://github.com/cosmos/ibc/pull/915) based on `ibc-rs`, I found that the `verify_upgrade_client` function of `ClientState` trait will NOT work when the client needs to use a proof verification algorithm other than Merkle proof.

https://github.com/cosmos/ibc-rs/blob/1c5b50b17894ef86c048cc8e874e09020f0a3bcd/crates/ibc/src/core/ics02_client/client_state.rs#L124-L131

As in NEAR protocol, the state proof is MPT proof rather than Merkle proof, we can not construct a Merkle proof for this function. But we can implement `verify_membership` and `verify_non_membership` functions for NEAR client like I did [here](https://github.com/octopus-network/ics12-near/blob/main/src/v1/client_state.rs#L287), because they are using generic data type for proofs.

## Solution Proposal

To resolve this issue, the proposed solution is to change the data types of `proof_upgrade_client` and `proof_upgrade_consensus_state` to `CommitmentProofBytes`, similar to the design of `verify_membership` and `verify_non_membership`. This modification will allow the implementation of clients to choose their own verification algorithms.

**Comment by Farhad-Shabani** [comment]
We will handle it through #748
Thanks a lot for pointing this out :pray:
