### ISSUE TITLE
Remove `ValidationContext::host_timestamp()`

### ISSUE THREAD

**Issue by plafer** [cosmos/ibc-rs#784]
We should implement this function ourselves in terms of `host_height()` and `host_consensus_state()` (see [basecoin-rs](https://github.com/informalsystems/basecoin-rs/blob/11565218e43388e8f4b6919400313eecfaa88458/src/modules/ibc/impls.rs#L420-L424)), since there are no other valid ways to do it. It should no longer be part of the trait.

**Comment by Farhad-Shabani** [comment]
This reminded me of another issue I came across in IBC-go (https://github.com/cosmos/ibc-go/issues/3957), which is kind of related to #728 as well. As in both places, we assume that the `timestamp` necessarily comes from a `ConsensusState` definition.

IBC-go does things a bit differently when it comes to getting timestamps - they use a method called [`GetTimestampAtHeight`](https://github.com/cosmos/ibc-go/blob/main/modules/core/exported/client.go#L65-L71) under the `ClientState` interface. Given that light clients can have access to the `ConsensusState` store, a client can choose whether to use `ConsensusState` for getting the `timestamp` (e.g. [here](https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/07-tendermint/client_state.go#L61-L74)) or not where the Wasm light clients can be an example.

Anyhow, worth evaluating the IBC-go design too, particularly as I see the `host_timestamp` in our implementation is only called by the `ClientState` impls.

**Comment by Farhad-Shabani** [comment]
Closing this issue, as with the experience we gained from recent integration projects, specially considering [this spec change](https://github.com/cosmos/ibc-rs/issues/1299), the `host_consensus_state` is not required anymore. Therefore, the `host_timestamp` does not necessarily comes from `host_consensus_state`, though if a host want to go that way, still can.
