### ISSUE TITLE
Prioritize redundant packet checks for better performance in multi-relayer scenarios

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#817]
## Background

Originally derived from a conversation with the author of [“Analyzing the Performance of IBC”](https://arxiv.org/abs/2303.10844)

## Concern
Having a single instance of relayer works better compared to multiple relayers, as the on-chain processing cost of redundant packets lowers the overall IBC performance.  

## Proposal

A resolution is to ensure checks for “already relayed packet” in places like [here](https://github.com/cosmos/ibc-rs/blob/7191d8839eb2ff8c9e95a455a5727e233ea2b28a/crates/ibc/src/core/ics04_channel/handler/recv_packet.rs#L49-L75), and [here](https://github.com/cosmos/ibc-rs/blob/7191d8839eb2ff8c9e95a455a5727e233ea2b28a/crates/ibc/src/core/ics04_channel/handler/acknowledgement.rs#L141-L150) get done before any other validation/execution processes as much as possible. This should lower the number of soft and, more importantly, hard checks against the store in redundant packet cases.

**Comment by muku314115** [comment]
Would it make sense to make this a more generic utility and perhaps use it for other relay cases like transfer receiving logic?

**Comment by Farhad-Shabani** [comment]
> Would it make sense to make this a more generic utility and perhaps use it for other relay cases like transfer receiving logic?

Certainly. When a receiving transfer packet enters ibc-rs, it touches one of the two mentioned locations ([this](https://github.com/cosmos/ibc-rs/blob/7191d8839eb2ff8c9e95a455a5727e233ea2b28a/crates/ibc/src/core/ics04_channel/handler/recv_packet.rs#L49-L75)) as well. Thus, handling that should address those use cases too.

**Comment by expertdicer** [comment]
Hello guys, could I take issue and one question: should I place the `Verify packet commitment` action before this line too?  https://github.com/cosmos/ibc-rs/blob/7191d8839eb2ff8c9e95a455a5727e233ea2b28a/crates/ibc/src/core/ics04_channel/handler/acknowledgement.rs#L118

**Comment by Farhad-Shabani** [comment]
> Hello guys, could I take issue

Of course, appreciate that.

> and one question: should I place the `Verify packet commitment` action before this line too?

That's right. Additionally, we should handle a similar case for the `recv_packet` process as well. Bringing [this](https://github.com/cosmos/ibc-rs/blob/7191d8839eb2ff8c9e95a455a5727e233ea2b28a/crates/ibc/src/core/ics04_channel/handler/recv_packet.rs#L49-L75) check up right after [this line.](https://github.com/cosmos/ibc-rs/blob/99020c2a8578858c15da5c7fd27e1d4a567c8a63/ibc-core/ics04-channel/src/handler/recv_packet.rs#L158)

**Comment by Farhad-Shabani** [comment]
This is closed with this note: https://github.com/cosmos/ibc-rs/pull/1007#issuecomment-1853977941
