### ISSUE TITLE
Feature `mocks-no-std` is missing in Cargo.toml

### ISSUE THREAD

**Issue by bluele** [cosmos/ibc-rs#819]
## Bug Summary

Even though this feature was removed by PR #700, some code still refers to this: https://github.com/search?q=repo%3Acosmos%2Fibc-rs%20mocks-no-std&type=code

Was the removal of this feature intended in the PR?

**Comment by plafer** [comment]
I believe we meant to remove all the references to it. @Farhad-Shabani can you confirm?

**Comment by Farhad-Shabani** [comment]
> I believe we meant to remove all the references to it. @Farhad-Shabani can you confirm?

Correct, `mock-no-std` was originally designed to toggle the `cfg_if` dep on or off, which since #700 has been removed. Can get rid of these traces.
