### ISSUE TITLE
serde_json uses floats that may be disallowed in WASM

### ISSUE THREAD

**Issue by tzemanovic** [cosmos/ibc-rs#850]
## Bug Summary

In https://github.com/anoma/namada we're compiling an IBC transaction code to WASM and found that the usage of `serde_json` includes a number parses that uses floats even when floats are not being used (e.g. from `fn send_transfer_execute` from `crates/ibc/src/applications/transfer/relay/send_transfer.rs`). This is problematic for deterministic WASM execution in which floats are disabled. From this https://github.com/serde-rs/json/issues/567 there's a fork that feature-gates floats at https://github.com/nearprotocol/json that can be used in place

**Comment by Farhad-Shabani** [comment]
Thanks @tzemanovic for opening this issue. 
There is a [PR](https://github.com/cosmos/ibc-rs/pull/803) that should take care of this problem too. We place a higher priority on getting it done.

**Comment by tzemanovic** [comment]
that's great, thanks @Farhad-Shabani ! Using https://github.com/CosmWasm/serde-json-wasm looks like a good idea, I tried to use https://github.com/nearprotocol/json but I could still see some floats left in wasm
