### ISSUE TITLE
`ibc-derive` does not work if only depend on `ibc-core`

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-rs#999]
## Description
The current implementation of `ibc-derive` exclusively supports projects dependent on the `ibc` meta-crate, where [the required types](https://github.com/cosmos/ibc-rs/blob/4421b0dcd6eab6c914b8c5a7d45817b1edb6b2ce/ibc-derive/src/utils.rs#L11-L75) for implementing `ClientState` and `ConsensusState` traits are imported directly from `ibc`.
This poses a limitation as not all projects necessarily rely on `ibc`. To enhance the utility of `ibc-derive`, it should support projects that may depend on the `ibc-core` (or even `ibc-core-client`) crates.

**Comment by seanchen1991** [comment]
Does addressing this issue just involve updating the import paths for all of the functions in the `Imports` module?

**Comment by Farhad-Shabani** [comment]
> Does addressing this issue just involve updating the import paths for all of the functions in the `Imports` module?

It's a bit trickier. The macro needs to manage three distinct group of paths, depending on which of the `ibc`, `ibc-core`, or `ibc-core-client` crates a user selects.

**Comment by mina86** [comment]
Related: https://github.com/cosmos/ibc-rs/pull/1017
